# Generated by Django 4.1.3 on 2022-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='esp32_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led1', models.IntegerField(max_length=50)),
                ('temp1', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Table_ESP32',
            },
        ),
    ]
