# Generated by Django 4.1.2 on 2022-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_esp32_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upld_sbdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fileName', models.CharField(max_length=550)),
            ],
            options={
                'db_table': 'Upload_Table',
            },
        ),
    ]
